### ISSUE TITLE
Dimension of Ytrain

### ISSUE THREAD

**Issue by wl935** [KaishuaiXu/iqrnn#1]
May I ask why you set the dimension of Ytrain as (900, 99) in the demo? It seems that this should be (900, 1).

**Comment by kaishxu** [comment]
> May I ask why you set the dimension of Ytrain as (900, 99) in the demo? It seems that this should be (900, 1).

It is the setting of the original paper. The author constructs the loss function combining losses from multiple quantile levels. So, I give an example of 99 quantile levels, and you can use any quantile combination if you edit the loss function in my code.

**Comment by wl935** [comment]
Many thanks for your quick reply. Yes, I saw that you define 99 quantile levels in the qloss function, but it still seems strange if we use 99 response variables to train the model. The dimension of Xtrain is (900, 3), which means that we have three features as our predictor variables, if we set the dimension of Ytrain as (900,1), we can get 99 predicted quantiles by using your demo code.
